version: '3'
services:
  web:
    image: nginx:latest
    volumes:
      - ${pwd}/site.conf:/etc/nginx/conf.d/site.conf
    ports:
      - "80:80"
    links:
      - phpfpm

  phpfpm:
    image: php:fpm
    volumes:
      - ./code:/usr/share/nginx/html
    ports:
      - "9000:9000"